config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true, length: { minimum: 6 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

     private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.all
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.new
  end

   private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add Movies to the list</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%#= f.error_notification %>
    <%#= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Add movie", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>All Movie List</h1>
  <ul class="list-group">
  <% @list.each do |item| %>
    <li class="list-group-item"><%= link_to item.name, list_path(item.id) %></li>
  <% end %>
</ul>
<hr>
<%= link_to "Add new list", new_list_path %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add List</h1>
  <%= simple_form_for [@movie, @list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Add a list", class: "btn btn-primary" %>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>

  <ul class="list-group">
    <% @bookmarks.each do |bookmark| %>
      <li class="list-group-item"><%= bookmark.movie.title %><br><%= bookmark.comment %></li>
    <% end %>
  </ul>
  <%= link_to "Add a movie", new_list_bookmark_path(@list) %>
  <%= link_to "Back to all lists", lists_path %>
</div>